---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: eck-operator
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: elastic-dw
        namespace: ${workspaceNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: elasticsearch-workspace