---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: logstash
      version: 8.7.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-dw
        namespace: ${workspaceNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: elasticsearch-workspace