---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluent
  namespace: elasticsearch-workspace
spec:
  chart:
    spec:
      chart: eck-operator
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: confluent
        namespace: elasticsearch-workspace
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: elasticsearch-workspace