apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: my-kibana
spec:
  version: 8.7.1
  count: 1
  elasticsearchRef:
    name: my-elastic-cluster
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: SERVER_BASEPATH
            value: /kibana
  config:
    server.publicBaseUrl: https://elastic.demo-app.cloud