---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: confluent-dw
  namespace: ${releaseNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: unsupported
spec:
  url: "${helmMirrorURL:=https://packages.confluent.io/helm}"
  interval: 5m