---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: elastic
  labels:
    kommander.d2iq.io/dkp-airgapped: unsupported
spec:
  url: https://helm.elastic.co
  interval: 5m