---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elastic-dw
  namespace: ${releaseNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: unsupported
spec:
  url: "${helmMirrorURL:=https://helm.elastic.co}"
  interval: 1m
  timeout: 1m