---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluent
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: confluent-for-kubernetes
      version: 0.771.13
      sourceRef:
        kind: HelmRepository
        name: confluent-dw
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: elasticsearch-workspace