apiVersion: dispatch.d2iq.io/v1alpha2
kind: GitopsRepository
metadata:
  name: my-confluent
  namespace: elastic-project
  cloneUrl: https://github.com/d2iq-ps/elasticsearch
  template:
    path: ./artifacts/my-kibana
    ref:
      branch: main
    suspend: true
